### ISSUE TITLE
https対応

### ISSUE THREAD

**Issue by faithandbrave** [boostjp/site#117]
2017年1月1日から、iOSでhttpsのページしか見れなくなることもあり、cpprefjp/boostjpのGitHub Pagesをhttpsに対応しようと思います。

作業としてはGitHub Pagesリポジトリの設定でhttpsのチェックボックスをオンにするだけなのですが、念のためアナウンスとしてIssueを立てました。

- [Securing your GitHub Pages site with HTTPS - GitHub Help](https://help.github.com/articles/securing-your-github-pages-site-with-https/)

問題なければ、12月2日にその対応をし、動作しているようであれば本Issueを閉じようと思います。
懸念事項があればそれまでにコメントください。

**Comment by faithandbrave** [comment]
関連Issue : https://github.com/cpprefjp/site/issues/374

**Comment by melpon** [comment]
リダイレクトされるとはいえ、httpサイトに行くのは嬉しくないので、https化した際に以下のURLもhttpsに直しておいた方が良さそう。

```
README.md|4 col 91| このリポジトリは、Boost C++ Librariesの日本語情報サイト[boostjp](http://boostjp.github.io/)のMarkdownソースです。
```

（"boostjp.github.io" で *.md ファイル全体を検索した）

**Comment by faithandbrave** [comment]
httpsに強制リダイレクトするよう設定しました。2〜3日様子を見て、問題なさそうであればこのIssueを終了します。

**Comment by e-kwsm** [comment]
c092eca (boostjp/boostjp.github.io@70ec0c7) が https://boostjp.github.io/tips/xml.html#read に（まだ）反映されないのですが，何か関係ありますか．

**Comment by melpon** [comment]
GitHubからこんなメールが来てました。

```
The page build failed with the following error:

unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by melpon** [comment]
HTMLが何かinvalidなのかなーって思ってvalidatorに食わしたら全く関係ない場所で大量にエラー出てて、これどうやって動いてたんだレベルの酷さ…

**Comment by e-kwsm** [comment]
今見たら変更が反映されていました．

**Comment by faithandbrave** [comment]
@melpon validatorのエラーがあったら、別Issueに貼り付けておいてもらえますか。(おそらくBoostの翻訳ドキュメントあたりだと思いますが)
httpsとは関係なさそうで、そちらは問題なく動いているようなので終了します。
