### ISSUE TITLE
Boost.SmartPtrの翻訳ドキュメントを移植する

### ISSUE THREAD

**Issue by faithandbrave** [boostjp/site#23]
from : <https://github.com/boostjp/old_boostjp_site/tree/master/libs/smart_ptr>
to : archive/boost_docs/libs

**Comment by graighle** [comment]
やります．

**Comment by faithandbrave** [comment]
あ、 @graighle さんにはpush権限をお渡しするようこちらから招待しています。GitHubからメールが行ってると思うので、よければ承認をお願いします。
そうしたら、Issueの担当を直接アサインできますので、「やります」宣言は不要です。

**Comment by graighle** [comment]
おお，了解です．

**Comment by Flast** [comment]
6cbba497550a3cf78ec720a7bf4e947bc4f9998f　これは未完ですか？

**Comment by Flast** [comment]
http://boostjp.github.io/archive/boost_docs/libs/smart_ptr/smart_ptr.html
テーブル壊れてそう

**Comment by graighle** [comment]
ありがとうございます！
直しました！
（すぐWikiに反映されなかったので確認するのをそのまま忘れちゃってました・・・）．
