### ISSUE TITLE
メーリングリストページのアーカイブ先が切れてる

### ISSUE THREAD

**Issue by h-sao** [boostjp/site#426]
Gmaneサービスって終了してますので、メーリングリスト `site/mailing-lists.md` のページに記載しているGmane利用のアーカイブリンクが軒並み切れています
（これに限った話ではないかもしれませんが、目に留まったときに時に気になりましたので）
[リンク切れ]と注釈をいれるか、リンクを削除するか、もしくは新たなアーカイブ先があるならそれを記載するかしたほうが良いのかなと思いました
（ちょっと調べた感じでは新規アーカイブ先は判りませんでした）
もしコンテンツの修正をする方針であればわたしの方でPR出せますが、どうするのがいいでしょう…？
> 個人的にはアーカイブ先が分からないなら今のURLは残しておいて[リンク切れ]と書くのが良いのかな？と思いました

**Comment by faithandbrave** [comment]
mailmanにリンクするのがいいですね。
https://www.boost.org/community/groups.html

**Comment by h-sao** [comment]
あぁ本家もGmaneのリンクのままですね
そこのページ内リンクを張ることにします
