### ISSUE TITLE
PRやコミットなどを行う際の基準について

### ISSUE THREAD

**Issue by ROCKTAKEY** [boostjp/site#569]
cpprefjp (https://cpprefjp.github.io/start_editing.html) に比べ、boostjp (https://boostjp.github.io/editors_doc/start_editing.html) ではコントリビュートのガイドライン的な位置付けのページが簡素ですが、 そこで触れられていない、たとえばPRが必要がどうか、コミットメーセージの書式をどうするか、のような基準はcpprefjpと同様と考えてよいのでしょうか。

このあたりがどこかに明記されていると、コントリビュートする際の戸惑いが少なくなると思いました(cpprefjpとは運用方針が異なるのであれば、文書化する手間と天秤にかける必要がありますが)。

**Comment by faithandbrave** [comment]
同様だと思っていただいて大丈夫です。
なかなか手が回っていないです…
