### ISSUE TITLE
1.61.0リリースノート: Context

### ISSUE THREAD

**Issue by Flast** [boostjp/site#62]

**Comment by faithandbrave** [comment]
<https://github.com/boostorg/website/commit/ba8a40af4db00da28ffb47d6f5bc7ad6d02165fb>
[[Coroutine] What happened to WINFIBERS?](http://thread.gmane.org/gmane.comp.lib.boost.devel/266603)

んー、どうしたものか。上記メーリングリストでのやりとりで結論がでたら対応かな。

現状では、「破壊的変更 Windows Fiber APIのサポートを削除。これはFiberのAPIが非推奨であったためである」という内容で記載することになりそうですが、いつから非推奨であったのか、この突然の削除変更が適切なものであるかなど、議論の結論を待つことになりそうです。

**Comment by Flast** [comment]
Oliverが破壊的変更するのは今に始まったことじゃないので、諦めるかリリースまでに徹底抗戦しないといけないと思います。
今リリースだとFPUの保存もしなくなった件について、多分Oliver戻す気はなさそうですし。 https://svn.boost.org/trac/boost/ticket/12114

**Comment by faithandbrave** [comment]
あーいえ、私の意図としては、削除された理由を付加情報としてこちらのページに記載したい、というものです。Fiber APIが非推奨という情報が出ていましたが、「それほんとに非推奨なの？」という話も出ていてその結論を待ってからでいいかなと。

**Comment by Flast** [comment]
なるほど、了解しました。

**Comment by faithandbrave** [comment]
とくに話が進んでないみたいなので、メーリングリストのスレッドへのリンクだけ貼って、理由表記なしにしますかね。

**Comment by Flast** [comment]
もうcloseしたのでそれでいいと思います

**Comment by faithandbrave** [comment]
https://github.com/boostorg/website/pull/152
