### ISSUE TITLE
1.61.0リリースノート:  テストコンパイラ一覧

### ISSUE THREAD

**Issue by Flast** [boostjp/site#72]

**Comment by faithandbrave** [comment]
このタスクは、ベータ版がリリースされたあとにやるのがよいでしょうか。

**Comment by Flast** [comment]
基本的にはいつでも良いと思いますよ　ただ、たまに変更されたりするので他のと同様に追う必要はありますね

**Comment by faithandbrave** [comment]
りょうかいです。手をつけつつ、更新が止まったころにissueをクローズします。
